---
server:
  port: 8888
spring:
  security:    user:      name: RajTomar
      password: RajTomar
  cloud:    config:      server:        git:          uri: https://github.com/Raj-Tomar/spring-cloud-config-wa-tolls
          #username: Raj
          #password: RajTomar
          search-paths:          - 'station*'
          repos:            perfs:
              pattern:                - "*/performace"
              uri: https://github.com/Raj-Tomar/spring-cloud-config-wa-tolls-performace
              search-paths:                - 'station*'            